# Generated by Django 3.2.12 on 2025-03-27 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20250327_0124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='year',
        ),
    ]
