# Generated by Django 3.2.12 on 2025-03-27 01:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cast',
            field=models.TextField(blank=True, null=True, verbose_name='В ролях'),
        ),
        migrations.AddField(
            model_name='product',
            name='country',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='product',
            name='date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Дата'),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='director',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Режиссер'),
        ),
        migrations.AddField(
            model_name='product',
            name='play',
            field=models.IntegerField(blank=True, help_text='В секундах', null=True, validators=[django.core.validators.MinValueValidator(60)], verbose_name='Продолжительность'),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='product',
            name='year',
            field=models.ImageField(null=True, upload_to='', validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2025)]),
        ),
    ]
