# Generated by Django 3.2.12 on 2025-05-05 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20250505_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='', max_length=40, verbose_name='Псевдоним'),
        ),
        migrations.AddField(
            model_name='section',
            name='slug',
            field=models.SlugField(default='', max_length=40, verbose_name='Псевдоним'),
        ),
    ]
